### ISSUE TITLE
document additional validations needed for "v2" forecast updates

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#1230]
The idea here is to create a new kind of submission where a team wants to update a forecast but we don't want the original forecast to be lost in the bowels of GitHub. So one idea is to allow for submissions of second files that would stand along-side the original submission and maybe would have `_v2` appended to the existing filename. What would we need to do to make this happen? Likely lots of small changes in different places. Can we document them here and then will make some separate issues?

- would need to modify validations to allow `_v2.csv` at the end of filenames
- decide which version to upload to Zoltar
- would we want to keep track of which version was used in ensemble and visualization? 
- if/when we implement this, would be nice to go back and create files in cases where this happened.
- maybe we provide a 24 hour buffer after the Monday deadline as the cut-off for when a v2 is needed. (not necesarily programmatic, could just be something PR approvers check for)

Assigning many people to solicit wide feedback.

**Comment by elray1** [comment]
Update functions in `covidHubUtils` package with ability to specify which version to read in ("original", "latest", or specific version)

**Comment by hannanabdul55** [comment]
I will try writing down the changes involved with the `_v2` idea from the areas I am familiar with: 

### Visualization
- The visualization build scripts (`build.js`, `parse-data.js` and `convert_forecasts.py`)  should be modified to parse only the latest forecast files (or any other method adopted)
- Once this is done, as far as I can see, all downstream tasks remain unaffected.

### Github Actions
- **PR validation**
  - Incorporate the `_v2` suffix in all the places where we read forecast files.
  - If there is an update to a forecast file, it **should** have a `_v[0-9]` suffix. Also, possibly fail the validation check if there is an update to a forecast file (as we are handling it now with the suffix)? 
  - Since the suffixed filename would not be present in `validated_files.csv`, we would not have to make any changes in this part of the logic. 
- **Zoltar Upload**
  - Goes back to my question about tracking updates on Zoltar, a big chunk of the logic would depend on what we decide on this. 
  - In determining the new forecast updates, the logic to determine the forecast files will need to accommodate the new `_v2` suffix. 

- **Github Deploy**
  - This action will not change if we do the changes listed under the [visualization](#Visualization) section. 
  - Though, one enhancement we can make is to publish a tag for the commit used for the weekly deployment. This can help us easily keep a tab of the code and forecasts used for every week and can be accessed under the "Releases" section of the GitHub page. 

## Additional questions
Some questions that also come up from my side: 
- Should we also keep track of updates on Zoltar too? 
- Should we fail validations if an update was done to a much older forecast (beyond the past n submission)?

**Comment by matthewcornell** [comment]
WRT Zoltar, we have no version feature right now, so in the short term we'd need to decide the single file to upload for the forecast. Longer term, we'd need to meet to discuss implementation approaches. OTTOMH, we could loosen the restriction of one Forecast per TimeZero, which would give us versions. However, any code that deals with forecasts, such as downloading and scoring, would have to make decisions re: which version to use. My initial thought is that this would get complicated quick...

**Comment by Serena-Wang** [comment]
Shiny app
- update function to read the latest forecast from each team
- add 'version' in all plots and tables

  - a 'version' column will be added in tables in 'latest_location', 'latest_targets' and 'latest_quantiles'

  - add 'version' filter in 'latest_viz' (or rename this tab to 'viz_by_version', or add a new tab to compare all versions)

  - maybe leave 'latest_viz_by_location' unchanged. So it is comparing the latest forecasts from each team.

- the first run of the app will take longer if we are reading in all versions of forecasts

**Comment by eycramer** [comment]
Weekly reports - will these be updated based on model changes? 
      Maybe we'd need to include two versions on the website? 

Otherwise my main concern is on the scoring data from Zoltar and making sure that the zoltr package can export multiple versions of the scored data (original and updated scores)

**Comment by jbracher** [comment]
I would find it helpful to document when these updates were made as it makes a big difference if they were made before new observations came in or after. There was at some point the idea of adding the date to the file name, but that seems to have been abandoned. An alternative would be to allow for an optional column `commit_date` or similar inside the file.

**Comment by jarad** [comment]
I feel like there are two issues within this issue: 

1. Should we allow teams to submit forecast revisions. 
2. If yes, how should we implement those revisions. 

For the first issue on whether revisions should be allowed there are teams who are on both sides of the issue. On the "no revisions allowed" side, there is a desire to ensure that forecasts are accurate given the data available at that time and to promote good practice in developing code and checking forecasts. On the "yes revisions should be allowed side", there is a desire for forecasts to represent the algorithm (when implemented correctly). Thus, the divide is a difference between whether the Hub exists for operational (i.e. helping to forecast COVID-19 in the US) vs research (understanding how algorithms perform). As a Hub, we are balancing these two perspectives.

For historical perspective, we intended to not allow revisions, but when teams have mentioned they found a bug in their code, we have had a hard time saying no to their revision. As mentioned earlier, allowing revisions makes forecasts more representative of the algorithm used, but also removes erroneous forecasts from the public facing visualization. The downside is that teams could cheat by using more recent data and thereby improve their forecasts. The reason for each forecast revision has been documented in the pull request for that revision. Generally, the the number of revisions for a particular team have been small which is an indication that no teams have been abusing our leniency. Nonetheless, the Hub is interested in developing a solution that allows both forecasts submitted within a day of the `forecast_date` and revisions that are submitted later. (Note that revisions that are submitted within a day of the `forecast_date` should be treated as original forecasts since they are still adhering to the "rules".)

As stated, this issue suggests an approach where multiple forecast files would exist for a particular model with revisions indicated in the filename via and underscore ("_") followed by incremental numbers for further revisions. I'm not a huge fan of this solution as my file organization approach is strict about filenaming. In the Hub, the convention is `data-processed/team-model/YYYY-MM-DD-team-model.csv` adding a "_#" before the ".csv" would mean (with my current scripts) that the model would become `model_#` and thus be considered a different model. This problem was already mentioned by @Serena-Wang above in the shiny app scripts. But there are other downstream users, e.g. [538](https://projects.fivethirtyeight.com/covid-forecasts/), that may also have to update scripts. 

An alternative approach is to proceed as we currently are, i.e. the forecast file is overwritten. Since this is a git repo, the original forecast file and any revisions are available by looking at the git history which would require a bit more work.

An alternative approach would be to put revisions in a different directory, e.g. `data-revisions`. This directory would have the same structure as the `data-processed` folder. It seems to me that only one revision is necessary, i.e. if multiple revisions were required because, for example, multiple bugs were found, then the revision would just be overwritten until it faithfully represented the algorithm output. An upside of this approach is that the current system would continue as is (without any need to modify scripts) and would allow for both operational and research perspectives while allowing for teams to submit revisions.

**Comment by Khoale1096** [comment]
Since I'm most familiar with Zoltar uploading part, I will be expanding on what Abdul and Nick have already mentioned.

### Zoltar Upload

- Currently, forecasts with the `_v2` suffix will be viewed by the script as totally new forecasts (because of the new file name) and will upload them to Zoltar with `overwrite=False` flag, which will cause the upload to break since there's already a "v1" forecast on Zoltar. Therefore, the upload script needs to know which version is the "official" version to put on Zoltar. If we want to use `_v2` for Zoltar, it knows to set `overwrite=True` before uploading to replace the "v1", and should not re-upload "v1" at anytime. Or if we don't want to use `v1` for Zoltar, it also knows that it should never upload `_v2` and leave "v1" as it is.

**Comment by nickreich** [comment]
Summarizing and closing this issue for now. 

Currently, we require forecasts to be uploaded in the following format:
`data-processed/team-model/YYYY-MM-DD-team-model.csv`
where `team` and `model` must be the same in the directory and filename. We manually check that `YYYY-MM-DD` is either the day of or the day before the PR was submitted.

How about we require that forecasts submitted have the following filename structure:
`data-processed/team-model/YYYY-MM-DD-team-model_yyyy-mm-dd.csv`
where `YYYY-MM-DD` is the same as our current `forecast_date` that determines `target_end_date` etc... but now `yyyy-mm-dd` is the date submitted. We would enforce (ideally via GitHub timestamps, but maybe still just via manual check) that `yyyy-mm-dd` was the date the forecast was submitted to the hub or committed to git. The use of the `_` would allow us to clearly delineate the end of the `model` name and the beginning of the `submitted_date`. All forecasts would go in the data-processed directory.

This seems to be more specific and provides more info than the `_v2` idea, and also avoids confusion over multiple folders. But of course any utilities that read files from the `data-processed` folders would need to be modified to account for this change and possibly would need functionality to be able to read in "first", "latest", or some other specific file.


infrastructure that would need to be updated to accommodate new filename formats
  - file validation code on GitHub
  - zoltar upload scripts
  - visualization build scripts (build.js, parse-data.js and convert_forecasts.py) 
  - covidEnsembles
  - covidHubUtils
  - shiny app
