### ISSUE TITLE
Improve Zoltar upload performance using batch upload

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#1244]
Currently, we upload forecasts sequentially, implement batch upload.

**Comment by Khoale1096** [comment]
Zoltpy util.upload_batch_forecast() only uploads batch of forecasts in the same model, rather than allowing uploading batch of forecasts from different models. So a point for improving zoltar upload performance is this line in zoltpy util.upload_forecast(): [here](https://github.com/reichlab/zoltpy/blob/master/zoltpy/util.py#L133). Instead of polling the project from zoltar everytime we want to upload, we can just poll the project we want once and pass a reference to it. This will be my approach for improving the upload speed
