### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for Covid19Sim-Simulator

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#1311]
Hi @odalgic, 

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday August 29 was 182761, according to the data reported in the JHU CSSE repository at the end of day on Sunday August 30. The median of your submitted one week ahead forecast for cumulative deaths was 190,457, which suggests a forecast of 7696 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 6414.

We can imagine that this might happen for any of several reasons: for example, you may be using two different models to forecast incident and cumulative deaths, or you may be calculating cumulative deaths using a different reference data set or a different procedure for aggregating to the national level than we are (for reference, we describe our approach to calculating aggregated cumulative deaths based on the JHU CSSE data [here](https://github.com/reichlab/covid19-forecast-hub/wiki/Truth-Data). Regardless, we wanted to bring this discrepancy to your attention in case you were not aware of it.

Our goal is to make the ensemble forecasts of incident and cumulative deaths consistent with each other. This is only possible if the submitted forecasts of incident and cumulative deaths from each model are consistent with each other. Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by odalgic** [comment]
Hello,
Thank you for bringing this to our attention. This issue is caused due to our estimations not matching the reported data exactly. In future submissions, we will try to minimize the error between the reported data and model estimations by tweaking some of the model parameters, which should address this problem.

**Comment by elray1** [comment]
Hi @odalgic,

I hope you're doing well.  I'm following up on this issue because we noticed that there is still a discrepancy between the one-week ahead predictive medians for incident and cumulative deaths in your model submission.  At the national level this past week, the reported deaths at the end of the day on Sunday was 214370.  The median of your submitted one week ahead forecast for cumulative deaths was 215097, implying one week ahead incident deaths of 727.  However, the median of the submitted one week ahead forecast for incident deaths was 5257.  Do you have a sense of what is going on and whether it can be addressed?  Thanks!

**Comment by eycramer** [comment]
Hi @odalgic , 

Just bringing to your attention that the discrepancy this week between the 1 week ahead implied median (based on your cumulative death forecast) is 12,436 fewer deaths than the one week ahead calculated median from your incident death forecast.
