### ISSUE TITLE
Discrepancy between incidence and cumulative death forecasts for Columbia_UNC-SurvCon

### ISSUE THREAD

**Issue by eycramer** [reichlab/covid19-forecast-hub#2324]
Hi @shanghongxie , 

We are filing this issue because we noticed that your one-week ahead forecasts of incident and cumulative deaths didn't agree with each other this week. We would expect the one-week ahead predictive median for cumulative deaths to be approximately equal to the last reported cumulative deaths plus the one-week ahead predictive median for incident deaths, but this was not the case for your forecast submitted this week. The reported cumulative deaths for the US as of Saturday December 12th was 297,818 according to the data reported in the JHU CSSE repository at the end of day on Sunday December 13th. The median of your submitted one week ahead forecast for cumulative deaths was  366,801, which suggests a forecast of 68,983 incident deaths. However, this is not in agreement with the median of the submitted one week ahead forecast for incident deaths, which was 17,283.

We can imagine that this might happen for any of several reasons and we wanted to bring this discrepancy to your attention in case you were not aware of it.

Can you please respond to this issue with a description of why there is this discrepancy and also whether you have a plan to fix it? Thanks!

**Comment by shanghongxie** [comment]
Hi @eycramer,

Thank you for the reminder and detailed explanation. After checking our code, it turns out that we made a simple mistake in data manipulation when summarizing the result. The model itself works fine. We have fixed it and created a new pull request with the corrected file (issue #2327). We apologize for the inconvenience. Please feel free to let me know if you have any further questions. Thanks!
