### ISSUE TITLE
Add automatic labels for PRs

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#2807]
## Some labels to be added

- [x] Add a label ~`data-deletion`~ `forecast-updated` when a forecast in the `data-processed` folder is deleted/updated.  
- [x] Explore auto-merge of PRs for the simplest case of forecast additions.

**Comment by Serena-Wang** [comment]
It would be great if we could implement these checks in `data-submission` label:

- [ ] Make sure forecast files are submitted under a model folder in data-processed.
- [ ] For each PR, make sure people are modifying forecast files only for one model. It happened recently that a team mistakenly added other team's forecast files in their PR, after they pulled our main branch. So in this case, we need to ask the team to manually delete those files in their PR. But there might be an exception for teams like CU, because they often updated weekly forecasts for all their models in one PR.

**Comment by hannanabdul55** [comment]
Automerge is implemented in https://github.com/reichlab/covid19-forecast-hub-validations/commit/94a0835428429b2a917f3579bbd890f5e61793bf
