### ISSUE TITLE
add prediction intervals to tooltip

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#451]

**Comment by ayushkhd** [comment]
Based on discussion with Professor Nick - 
Two types of Tooltips - 
- [ ] For Actual data

- [ ] For predicted data

**Comment by ayushkhd** [comment]
One option could be to have the tooltip say something like:
week end: yyyy-mm-dd
observed: xxxx
forecasted: xxxx

**Comment by ayushkhd** [comment]
<img width="1440" alt="Screen Shot 2020-09-08 at 9 48 26 PM" src="https://user-images.githubusercontent.com/20081981/92545849-abbf8080-f26e-11ea-8695-c47695bd5aa5.png">
<img width="909" alt="Screen Shot 2020-09-08 at 10 00 38 PM" src="https://user-images.githubusercontent.com/20081981/92545850-ac581700-f26e-11ea-9626-01f8eda7a3bd.png">
<img width="836" alt="Screen Shot 2020-09-08 at 9 46 04 PM" src="https://user-images.githubusercontent.com/20081981/92545846-a9f5bd00-f26e-11ea-927c-89b4ee9f4438.png">

**Comment by ayushkhd** [comment]
Some options for adding week ending dates to tooltip hover

**Comment by ayushkhd** [comment]
My personal favorites

<img width="1440" alt="Screen Shot 2020-09-08 at 10 18 15 PM" src="https://user-images.githubusercontent.com/20081981/92547000-85e7ab00-f271-11ea-8cc8-72def357529c.png">
<img width="904" alt="Screen Shot 2020-09-08 at 10 15 01 PM" src="https://user-images.githubusercontent.com/20081981/92547013-8a13c880-f271-11ea-9eb1-f8d4f2c7085f.png">

**Comment by hannanabdul55** [comment]
@ayushkhd these look great! I like how the tooltip for the actual data shows the date now. One question about that - Is the date shown on the Actual tooltip the start of the week or end?  

Also, for the prediction panel on the right, I think it would make more sense to have the date on the header of the panel instead of adding "on `[date]`" suffix for all model entries. Concretely, We should remove the date text for each model entry and instead add it to the top header which says `3 ahead` (in the screenshot you attached above). Maybe something like `2 week ahead predictions ([from_date] - [to_date])` (If there is space).

**Comment by mzorn-58** [comment]
@nickreich @hannanabdul55 @ayushkhd   Can this be closed?

**Comment by nickreich** [comment]
I agree with @hannanabdul55 in terms of adding the tooltip language in the header of the panel. So where it says "3 ahead" now it would say something like "For week ending 2020-10-31" or something like this.

**Comment by jarad** [comment]
@ayushkhd original comment mentioned prediction intervals which I heartily support, but I don't see those anywhere in this discussion. One way to provide more space savings would be to round forecast, e.g. rather than reporting US incident deaths at 8,669 report 9k (8k-10k)* or actually just get rid of the point forecast and report (8k-10k). * If this is the prediction interval.

**Comment by nickreich** [comment]
I like the two-line-per-model tooltip example from @ayushkhd above. What about something like:

Header of tooltip: "Week ending YYYY-MM-DD"

Each model section of tooltip:
"model-abbr: point estimate
[lower-bound of shown interval] - [upper-bound of shown interval]"

So an interval were selected it might look like:
"IHME-CurveFit: 32,843
25,887 - 45,876"

And if no interval were selected it would just show:
"IHME-CurveFit: 32,843"

**Comment by ydhuang28** [comment]
Closing this. Enhancement added through [PR#2331](https://github.com/reichlab/covid19-forecast-hub/pull/2331) (above).
