### ISSUE TITLE
Zoltar script changes for the new metadata format

### ISSUE THREAD

**Issue by hannanabdul55** [reichlab/covid19-forecast-hub#581]
With the new metadata changes, we renamed some of the `model_abbr` as per the new specifications. The Zoltar script checks for existing models using `model_name`. Hence, the models are present, but since the file names changed, they are seen as "new" forecasts and fail because the model already has forecasts for that period, for example present in [this](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/172276721) travis log).  

A possible solution is to use `model_abbr` instead of `model_name` in the Zoltar [script](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/zoltar-scripts/upload_covid19_forecasts_to_zoltar.py#L52) to check for the presence of a model (and model comparison). But in this process, we could possible upload a completely new model to Zoltar if we rename `model_abbr`. Hence, we need a more robust process to do this.

**Comment by Khoale1096** [comment]
A suggestion would be using the model ID (for example here https://zoltardata.com/api/model/290/) in place of `model_name` or `model_abbr`. This way if a model change its `model_name` or `model_abbr`, the script can refer to the ID and know that this is not a "new" model and should update to the existing model

**Comment by Khoale1096** [comment]
Update 1: regarding the failure in this [build](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/172276721) that @hannanabdul55 mentioned, the upload script [here ](https://github.com/reichlab/covid19-forecast-hub/blob/master/code/zoltar-scripts/upload_covid19_forecasts_to_zoltar.py#L117) didn't set `overwrite` to `true`, so that's why it's giving error while trying to upload a forecast with a timezero that is already associated with another forecast on Zoltar. I have updated this uploading script to set this flag to `true` when cases like this happen. As a result, the forecasts from DetGrowth is successfully uploaded to Zoltar in this new [build](https://travis-ci.com/github/reichlab/covid19-forecast-hub/builds/172354981)

**Comment by hannanabdul55** [comment]
Great! thanks for the fix! Also @Khoale1096 , can we move away from `model_name` anyways? I think the `id` or the `model_abbr` would be a better way to identify models uniquely.

**Comment by hannanabdul55** [comment]
This change is done. Closing this.
