### ISSUE TITLE
Can't issue pull request

### ISSUE THREAD

**Issue by RobertWalraven** [reichlab/covid19-forecast-hub#735]
I'm trying to issue a pull request on a new file that is a replacement for one that failed earlier today, but the system is not letting me issue a pull request.   Also my folder from the reichlab/data-processed area is no longer there.

**Comment by nickreich** [comment]
Does your new file have valid targets? We have stopped supporting "daily inc/cum death" targets. And because your existing files had only those targets, we removed them.

**Comment by RobertWalraven** [comment]
Yes, the file conforms to the new requirements.   I uploaded a file with the same data last night and it failed because I had forgotten to delete a field in the header, but that has been corrected in the file 2020-07-04-RobertWalraven-ESG.csv.   The problem is not that a pull has failed on this new file, it is that I can't even make a pull and I don't know enough about GitHub to know what the problem might be.

**Comment by RobertWalraven** [comment]
Still having no luck trying to issue a pull request.

**Comment by RobertWalraven** [comment]
Looks like it just worked moments ago..

**Comment by RobertWalraven** [comment]
Nope.  I'm getting a "conflicting file" message with a LANL file listed.

**Comment by RobertWalraven** [comment]
Was able to issue a pull request, but it failed because it could not find my metafile.   Could this be because you deleted my folder from data-processed?

**Comment by hannanabdul55** [comment]
Can you upload it to your folder again?  It was removed after we ran a
script to migrate all forecast files to the new format and then since your
model ended up with no targets as per the new format, it deleted your
folder.
All you have to do is to reupload your folder with the new targets and you
should be good. As a suggestion, you can go back to your initial pull
request where you uploaded your metadata files and copy that back along
with the new forecasts into the same folder. Thank you!

Regards,
Abdul Hannan Kanji

**Comment by RobertWalraven** [comment]
I deleted and re-uploaded the metafile and the data file.   Still getting the message that it can't find my metafile in data-processed/RobertWalraven-ESG.
