### ISSUE TITLE
add inc case truth data to appropriate files

### ISSUE THREAD

**Issue by nickreich** [reichlab/covid19-forecast-hub#892]
I see already `data-truth/truth-Incident Cases.csv` but these are daily counts. Why not weekly? what piece of the architecture is using these files? Should we change them to be weekly? Also, can we pull in the county-level inc case data for USAFacts and NYT data?

**Comment by Serena-Wang** [comment]
We are using these truth files in the shiny app. Because state inc deaths were daily counts, I didn't aggregate them to weekly counts when I changed the code. County level inc case from USAFacts and NYT are all in `truth_usafacts-Incident (or Cumulative) Cases.csv `and `truth_nytimes-Incident (or Cumulative) Cases.csv` But county level data are not included in json files.

**Comment by RobertWalraven** [comment]
Since the truth data is the standard that teams can use to generate model data, it is important to keep the daily counts because some models such as mine may need that level of detail to make more accurate projections.   Reducing the data to weekly values would alter the frequency distribution of the data, so it would no longer be "raw" data.

What wasn't clear to me at first was exactly how you produced weekly numbers from the daily data.   It appears that what you do is average the days from Sunday through Saturday to get a weekly value for Saturdays, rather than using some other starting point for each week.  If that is correct, it would be useful for new teams to know that.

**Comment by jarad** [comment]
@RobertWalraven There is no expectation on our end that the data in the data-truth/ folder are the data that teams use to make forecasts. I agree that we do not want only weekly aggregation, but we may want both. 

The Sunday through Saturday aggregation was indicated within the data submission instructions, e.g. for [N wk ahead inc death](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#n-wk-ahead-inc-death). I have modified this document to include mention of this weekly aggregation in the [truth data section](https://github.com/reichlab/covid19-forecast-hub/blob/master/data-processed/README.md#ground-truth-data). 

@nickreich If this clears up your question, please close the issue. If not, please expand on your question.
